### ISSUE TITLE
endpoint ambigu

### ISSUE THREAD

**Issue by ichsanSandi** [2019-pemrogramanberbasiskerangkakerja-g/sistem-kehadiran-online-syavira-dara-aulia#2]
endpoint `GET /rekapmahasiswa/nrp/idsemester` tidak memberikan return value yang diinginkan, karena ambigu dengan endpoint `GET /rekapmahasiswa/nrp/idmatakuliah`
![Capture](https://user-images.githubusercontent.com/34672967/57984404-b8bace00-7a85-11e9-83cb-bb9daa589610.JPG)
![Capture2](https://user-images.githubusercontent.com/34672967/57984420-d8ea8d00-7a85-11e9-8b31-f15ffd365632.JPG)

**Comment by AuuTeaku** [comment]
DB dan query sudah diperbaiki
